// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/watch/watchlists": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Performs ADD, GET or DELETE Operation Based on ActionType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Executed ADG Operations",
                "parameters": [
                    {
                        "description": "Watchlist ADG Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFAdgToWatchlistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ADG Request Successful",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAdgToWatchlistResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "401": {
                        "description": "DataBase Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "404": {
                        "description": "User does not exist",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ActionType": {
            "type": "string",
            "enum": [
                "ADD",
                "DEL",
                "GET"
            ],
            "x-enum-varnames": [
                "ADD",
                "DEL",
                "GET"
            ]
        },
        "models.BFFAdgToWatchlistRequest": {
            "type": "object",
            "required": [
                "action",
                "scripId"
            ],
            "properties": {
                "action": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ActionType"
                        }
                    ],
                    "example": "GET"
                },
                "scripId": {
                    "type": "string",
                    "example": "BSE_2001"
                },
                "watchlistIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "models.BFFAdgToWatchlistResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/models.ActionType"
                },
                "message": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "watchlistNames": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WatchlistWithId"
                    }
                }
            }
        },
        "models.ErrorAPIResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "errors": {
                    "$ref": "#/definitions/models.ErrorMessage"
                }
            }
        },
        "models.ErrorMessage": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "models.WatchlistWithId": {
            "type": "object",
            "properties": {
                "watchlist_id": {
                    "type": "integer"
                },
                "watchlist_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "x-extension-openapi": "{\"example\": \"value on a json format\"}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "omnenest-backend",
	Description:      "Omnenest backend for watchlist micro-service (Middleware layer).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
