info:
  contact: {}
  description: Omnenest backend for watchlist micro-service (Middleware layer).
  title: omnenest-backend
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
    x-extension-openapi: '{"example": "value on a json format"}'
swagger: "2.0"
